name: CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

env:
  DOTNET_VERSION: 9.0.x

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Initialize
        id: init
        run: .\build\build.ps1 --exclusive --target Initialize

      - name: Restore NuGet packages
        run: .\build\build.ps1 --exclusive --target RestoreNuGetPackages

      - name: Build
        run: .\build\build.ps1 --exclusive --target Build

      - name: Scan code
        run: .\build\build.ps1 --exclusive --target ScanCode

      - name: Create package
        if: ${{ github.event_name == 'push' && env.SRC_CHANGED == 'true' }}
        run: .\build\build.ps1 --exclusive --target CreatePackage

      - name: Publish to NuGet Gallery
        if: ${{ github.event_name == 'push' && env.SRC_CHANGED == 'true' }}
        run: >
          dotnet nuget push .\output\*.nupkg
          --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
