name: DevSkim

on:
  push:
    branches: [master]
  schedule:
    - cron: 30 9 * * 1

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run DevSkim scan
        uses: microsoft/DevSkim-Action@v1

      - name: Upload DevSkim scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: devskim-results.sarif
